####################
# Title: Gen_CSEstRDS
# Author: Robert Petit
# Desc: Generates the CS Estimator (See Callaway and Sant'anna 2021) to load into other figures
# This is useful since the same estimation is used for a few figures and I want it all in one place
# Saving to an RDS is probably not the most efficient way to accomplish this
################
read_dta(here("Data/CSData.dta")) %>% 
  { list(
    CS_Vio = att_gt(yname = "lRatVio",
           tname = "year",
           idname = "fipsstat",
           gname = "GTime",
           data = .,
           #xformla = ~ i.id + i.date,
           est_method = "dr",
           control_group = "notyettreated",
           bstrap = FALSE,
           #biters = nboot,
           print_details = F,
           clustervars = NULL,
           panel=FALSE),

   CS_Mur = att_gt(yname = "lRatMur",
                   tname = "year",
                   idname = "fipsstat",
                   gname = "GTime",
                   data = .,
                   #xformla = ~ i.id + i.date,
                   est_method = "dr",
                   control_group = "notyettreated",
                   bstrap = FALSE,
                   #biters = nboot,
                   print_details = F,
                   clustervars = NULL,
                   panel = TRUE),

   CS_Rap = att_gt(yname = "lRatRap",
                   tname = "year",
                   idname = "fipsstat",
                   gname = "GTime",
                   data = .,
                   #xformla = ~ i.id + i.date,
                   est_method = "dr",
                   control_group = "notyettreated",
                   bstrap = FALSE,
                   #biters = nboot,
                   print_details = F,
                   clustervars = NULL,
                   panel = TRUE),

   CS_Aga = att_gt(yname = "lRatAga",
                   tname = "year",
                   idname = "fipsstat",
                   gname = "GTime",
                   data = .,
                   #xformla = ~ i.id + i.date,
                   est_method = "dr",
                   control_group = "notyettreated",
                   bstrap = FALSE,
                   #biters = nboot,
                   print_details = F,
                   clustervars = NULL,
                   panel = TRUE),

   CS_Prop = att_gt(yname = "lRatPro",
                    tname = "year",
                    idname = "fipsstat",
                    gname = "GTime",
                    data = .,
                    #xformla = ~ i.id + i.date,
                    est_method = "dr",
                    control_group = "notyettreated",
                    bstrap = FALSE,
                    #biters = nboot,
                    print_details = F,
                    clustervars = NULL,
                    panel = TRUE),

   CS_Rob = att_gt(yname = "lRatRob",
                   tname = "year",
                   idname = "fipsstat",
                   gname = "GTime",
                   data = .,
                   #xformla = ~ i.id + i.date,
                   est_method = "dr",
                   control_group = "notyettreated",
                   bstrap = FALSE,
                   #biters = nboot,
                   print_details = F,
                   clustervars = NULL,
                   panel = TRUE),

  CS_Aut = att_gt(yname = "lRatAut",
                  tname = "year",
                  idname = "fipsstat",
                  gname = "GTime",
                  data = .,
                  #xformla = ~ i.id + i.date,
                  est_method = "dr",
                  control_group = "notyettreated",
                  bstrap = FALSE,
                  #biters = nboot,
                  print_details = F,
                  clustervars = NULL,
                  panel = TRUE),
  
  CS_Bur = att_gt(yname = "lRatBur",
                  tname = "year",
                  idname = "fipsstat",
                  gname = "GTime",
                  data = .,
                  #xformla = ~ i.id + i.date,
                  est_method = "dr",
                  control_group = "notyettreated",
                  bstrap = FALSE,
                  #biters = nboot,
                  print_details = F,
                  clustervars = NULL,
                  panel = TRUE),
  
  CS_Lar = att_gt(yname = "lRatLar",
                  tname = "year",
                  idname = "fipsstat",
                  gname = "GTime",
                  data = .,
                  #xformla = ~ i.id + i.date,
                  est_method = "dr",
                  control_group = "notyettreated",
                  bstrap = FALSE,
                  #biters = nboot,
                  print_details = F,
                  clustervars = NULL,
                  panel = TRUE)
   )} %>%
  
  saveRDS(file=here("Data/CS_ATTGTList.RDS"))

